### PR TITLE
fix(#40): Fix seasons handling when loading collections from user summary

### PR DESCRIPTION
**Pull request by gjariot**

### CODE REVIEW

**Comment by Roguyt** [comment]
Hey,
Thanks for your pull request.

In order for us to accept it you'll need to respect the template we included https://github.com/Roguyt/node-epicsgg/blob/master/.github/PULL_REQUEST_TEMPLATE.md.

On the topic of your changes, I'll rather see them as two separate merge requests.
The mistype of the Collections interface isn't a breaking change, while the change of argument is one.

@SherloxTV What's your thoughts on this ? Should we change the method internally to fix it, or we keep it consistant by making a breaking change ?

**Comment by gjariot** [comment]
I see, indeed we can see this as two separator fixes. I'll do that!

However, I do not see breaking change in the argument: we still pass the same parameter type to the client (`string | number`). The only thing that changed is the parameter used in the Epics API call, which is hidden from implementations.

However, I could see breaking changes in the Collection interface though where someone could indeed rely on the fact that he expects a string from seasons.

**Comment by Roguyt** [comment]
> However, I do not see breaking change in the argument: we still pass the same parameter type to the client (string | number). The only thing that changed is the parameter used in the Epics API call, which is hidden from implementations.

Yes this is indeed true, I guess adding a TODO: for the next breaking change would do the job

> However, I could see breaking changes in the Collection interface though where someone could indeed rely on the fact that he expects a string from seasons.

At runtime it doesn't change much, but the type definition are technically false for anyone relying on them

Looking forward to your fixes 😄

**Comment by gjariot** [comment]
See #42 and #43

**Pull request closed without merging**
